### ISSUE TITLE
benchmarking sppy x scipy

### ISSUE THREAD

**Issue by MSardelich** [charanpald/sppy#6]
I am looking for Python alternatives regarding sparse matrix calculations.

I run a simple performance suite for sppy and found that **scipy is more than 2x faster than sppy**.

The code is below:

```
import sppy
import scipy.sparse as ss
import numpy as np

density = 0.01

m = 10000
n = 10000
a_sppy = sppy.rand((m, n), density, storagetype='row')
a_sppy_T = a_sppy.T
%timeit x = a_sppy.dot(a_sppy_T)
# 1 loops, best of 3: 12.9 s per loop

a_scipy = ss.rand(m, n, density=density, format='csr')
a_scipy_T = a_scipy.T
%timeit y = a_scipy.dot(a_scipy_T)
# 1 loops, best of 3: 5.72 s per loop
```

**Any trick to improve sppy performance?**

Best, M.

**Comment by charanpald** [comment]
This is a problem with the storage type of the resulting array. Essentially, internal casting to row types in this case takes up the extra time and yet it's not so easy to avoid doing this. I will try to come up with a fix in the next few days.

**Comment by MSardelich** [comment]
Thanks for your prompt response!
If it matters, I run the same omitting the `storagetype` parameter, and performance is similar (equal,  I would say).

**Comment by charanpald** [comment]
I've had a chance to take a look at the problem and there isn't a quick fix to speed things up unfortunately. Sppy uses the Eigen C++ library for matrix operations so I decided to time the equivalent matrix multiplications in raw C++ here: https://github.com/charanpald/sppy/blob/master/sppy/test/SparseMatrixExtTime.cpp . Here are the resulting timings (in seconds) on my machine as well as those from running your Python script: 

Eigen: 2.51
sppy: 3.64
scipy: 1.67

Note that the matrices we use are not exactly the same but I wouldn't expect a big change in timings even if we use identical matrices. 

So it looks like scipy is faster than Eigen even without the overhead introduced in sppy. My guess is that the sparse matrix representations are different which accounts for the gap in timings. In sppy there is an additional cost due to mis-casting matrices (e.g. cast to row type when the output is a column type). This sounds like a trivial problem to fix, but is quite challenging. 

If you happen to be knowledgeable about Cython/C++/Eigen it would be great if you could take a look to see if you had some ideas on how to speed things up. Otherwise, let me know if you need to know anything else.

**Comment by MSardelich** [comment]
Thanks a lot for all your attention.

To be completely honest, I have been trying to beat scipy performance for the last couple of weeks, using standard algorithms to matrix (sparse) x vector (dense) multiplications. No success. They really did a great job!

My next step is to directly wrap [Sparse BLAS](http://math.nist.gov/spblas/) from netlib in Python.

Although Sparse BLAS doesn't implement matrix (sparse) x matrix (sparse), but only matrix (sparse) x matrix (dense) multiplications, maybe it can be faster for spectral clustering tasks (where we want to diagonalize using Arnold re-start).

Usually, my main performance issues is when building/growing the Similarity matrix by chunks (hadoop/custom storage solution using Pytables) from the sparse feature vectors. This operation involves an **sparse matrix X sparse matrix multiplication**, and, in my case, is a simple dot product.
The _diag task_, once the Similarity matrix  was calculated, is relatively easy to deal with. 

Let me know, if you have any personal interest in writing such a wrapper.

I will take a close look at your Cython code, but only in the next couple of weeks :-( 

Cheers, M.
